name: cek_penyakit_rumput_laut
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_onboarding_slider: ^1.0.11
  bottom_sheet: ^4.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  http: ^1.1.2
  # permission_handler: ^11.1.0
  flutter_easyloading: ^3.0.5 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
